---
- hosts: aida
  become: yes

  pre_tasks:
    - name: Install Java and Maven
      apt:
        name: ['openjdk-11-jdk', 'maven']
        update_cache: yes
        state: latest
  roles:
    - name: kafka
    - name: sanitization
