# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.define "aida"
  config.vm.hostname = "aida"
  
  config.vm.provider "virtualbox" do |v|
      v.memory = 4000
      v.cpus = 2
  end

  # TODO Use rsync instead of virtualbox. Using virtualbox just for development.
  # config.vm.synced_folder "..", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  config.vm.synced_folder "..", "/vagrant", type: "virtualbox"

  # dashboard folders
  config.vm.synced_folder "../dashboard/vagrant", "/vagrant/vagrant", create: true
  config.vm.synced_folder "../dashboard/frontend", "/srv/frontend", create: true, type: "rsync", rsync__exclude: ['node_modules/']
  config.vm.synced_folder "../dashboard/backend", "/srv/backend", owner: "www-data"

  config.vm.network :private_network, type: "dhcp"
  # AIDA input port
  config.vm.network :forwarded_port, guest: 4164, host: 4164
  # REST API port
  config.vm.network "forwarded_port", guest: 7777, host: 7777
  # dashboard port
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # Spark web UI port
  config.vm.network "forwarded_port", guest: 4040, host: 4040
  # dashboard admin port
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Sometimes Vagrant does not install pip while using Ansible provisioning
  config.vm.provision :shell,
    inline: "apt-get update && apt-get -y install python-pip"

  config.vm.provision :ansible_local do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.install_mode = "pip3"
    # ansible.version = "2.6.3"

    ansible.inventory_path = "provision/ansible/inventory-local.ini"
    ansible.playbook = "provision/ansible/install-aida.yml"
    ansible.config_file = "provision/ansible/ansible.cfg"
  end

  config.vm.provision "ansible_local" do |dashboard|
    dashboard.verbose = "v"
    dashboard.playbook = "vagrant/playbook.yml"
    dashboard.version = "latest"
  end
end
