# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.define "aida"
  config.vm.hostname = "aida"
  
  config.vm.provider "virtualbox" do |v|
      v.memory = 2000
      v.cpus = 2
  end

  # TODO Use rsync instead of virtualbox. Using virtualbox just for development.
  # config.vm.synced_folder "..", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  config.vm.synced_folder "..", "/vagrant", type: "virtualbox"

  config.vm.network :private_network, type: "dhcp"
  config.vm.network :forwarded_port, guest: 4164, host: 4164

  # Some version of vagrant do not install pip while using Ansible provisioning
  config.vm.provision :shell,
    inline: "apt-get update && apt-get -y install python-pip"

  config.vm.provision :ansible_local do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.install_mode = "pip"
    ansible.version = "2.6.3"

    ansible.inventory_path = "provision/ansible/inventory-local.ini"
    ansible.playbook = "provision/ansible/install-aida.yml"
    ansible.config_file = "provision/ansible/ansible.cfg"
  end
end
