- name: Install Apache2
  apt:
    name: ["apache2", "libapache2-mod-wsgi", "python-configparser"]
    update_cache: yes
    state: latest

- name: Install dbus dependencies for python systemd-manager
  apt:
    name: ["dbus", "libdbus-glib-1-dev", "libdbus-1-dev", "python-dbus"]
    update_cache: yes
    state: latest

- name: Check for restapi installation folder {{ restapi_dir }}
  stat:
    path: "{{ restapi_dir }}"
  changed_when: false
  register: restapi_installed
- when: not restapi_installed.stat.exists
  block:
    - name: Copy restapi files into {{ restapi_dir }}
      command: "cp -r {{ restapi_repository_location }}  {{ restapi_dir }}"
      args:
          creates: "{{ restapi_dir }}"
    - name: Set {{ apache_user }} as owner of {{ restapi_dir }}
      file:
        dest: "{{ restapi_dir }}"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        recurse: yes
    - name: Install virtualenv for python
      pip:
        name: virtualenv
        executable: pip
    - name: Create python virtualenv
      pip:
        requirements: "{{ restapi_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"
        virtualenv_python: python
        virtualenv_site_packages: yes

- name: Create app config file {{ config_dir }}/rest.ini
  template:
    src: rest.ini.j2
    dest: "{{ config_dir }}/rest.ini"
    mode: 0644
    group: "{{ apache_user }}"
    owner: "{{ apache_user }}"

- name: Create Apache2 config file
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/sites-enabled/rest-aida.conf
    mode: 0777

- name: Create Apache2 config file
  template:
    src: apache2_ports.conf.j2
    dest: /etc/apache2/ports.conf
    mode: 0644

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
