# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171130_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='widget',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='widget',
            name='panel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Panel'),
            preserve_default=False,
        ),
    ]
