# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171201_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='type',
            field=models.CharField(default='TABLE', max_length=50),
            preserve_default=False,
        ),
    ]
