# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180502_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='alias',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
