# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180502_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='panel',
            name='panel_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PanelGroup'),
        ),
    ]
