# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_widget_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='data_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
