# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181002_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='data_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
