# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181002_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('config_json', models.TextField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('visible', models.BooleanField(default=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Panel')),
            ],
        ),
    ]
