# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='include_filter',
            field=models.BooleanField(default=True),
        ),
    ]
