# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_panel_include_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='description',
        ),
    ]
