# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_component_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
