# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_component_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='WidgetGroup',
        ),
    ]
