# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181105_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetgroup',
            name='config_json',
        ),
    ]
