# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_widgetgroup_config_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='external_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panel',
            name='external_link_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
