- name: Install sqlite3
  apt: 
    name: sqlite3

- name: Create directory
  file:
    path: "{{ database_dir }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Check if database exists
  stat:
    path: "{{ database_path }}"
  register: db

- name: Create empty datbase
  command: "sqlite3 {{ database_path }} 'CREATE TABLE rule (id INTEGER PRIMARY KEY, inserted DATETIME DEFAULT CURRENT_TIMESTAMP, rule TEXT NOT NULL, support INTEGER, number_of_sequences INTEGER, confidence REAL, active INTEGER DEFAULT 0, comment TEXT, database TEXT, algorithm TEXT )'"
  when: db.stat.exists == False

- name: Set permissions
  file:
    path: "{{ database_path }}"
    mode: 0666
